# Generated by Django 5.2.17 on 2026-10-06 07:48

import django.core.validators
import django.db.models.deletion
import schedule.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, validators=[schedule.validators.validate_course_code], verbose_name='Код')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hours', models.PositiveIntegerField(default=36, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Часы')),
            ],
            options={
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, validators=[schedule.validators.validate_person_name], verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Кафедра')),
                ('phone', models.CharField(blank=True, max_length=12, validators=[schedule.validators.validate_phone], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['full_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, validators=[schedule.validators.validate_person_name], verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('group', models.CharField(max_length=30, verbose_name='Группа')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='schedule.course', verbose_name='Курсы')),
            ],
            options={
                'ordering': ['full_name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='schedule.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('office', models.CharField(blank=True, max_length=30, verbose_name='Кабинет')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='schedule.teacher')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gte', 1), ('hours__lte', 500)), name='course_hours_range'),
        ),
    ]
